### ISSUE TITLE
Required fields should not permit blank values as a default

### ISSUE THREAD

**Issue by bjohare** [Cadasta/django-jsonattrs#1]
In the [Attribute](https://github.com/Cadasta/django-jsonattrs/blob/master/jsonattrs/models.py#L179) model there should be a validation check to ensure that required fields can not be set with a blank value. Currently the default field is set to `blank=True` which means a value must be set, typically the empty string. However if the attribute is also marked as required but no value is supplied, the default will be accepted as the value. This is probably an unintended side effect as typically if a field is required then a value should be supplied?

**Comment by ian-ross** [comment]
Yeah, this is definitely a bit of a wart.  I'll sort it out one way or another.  My original idea was that fields that were required would have to have a default value supplied for them in the schema (and I think this is checked when you make a schema), but that's not really the best way for things to work.  As you say, a "required" field should mean that a value has to be supplied.

**Comment by ian-ross** [comment]
I've added validation checks for this, although I'm still not quite 100% sure that the behaviour is _exactly_ correct.
