### ISSUE TITLE
Schemas are not loaded when creating new instances

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/django-jsonattrs#3]
When creating a new model instance the schemas are not loaded correctly. 

[Inside `AttributeModelForm. add_attribute_fields`](https://github.com/Cadasta/django-jsonattrs/blob/master/jsonattrs/forms.py#L43-L44), schemas a loaded from the instance because `pk` is an empty string and not `None`.

I assume the condition should be `if self.instance.pk:` instead.

**Comment by ian-ross** [comment]
Let me look at this.  That whole bit of code is something of a rat's nest.
