### ISSUE TITLE
Form fields are always required

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/django-jsonattrs#7]
All form fields created by json_attrs are always required, because Django's form fields are required by default. 

When forms fields are created the `required` argument should be added and set to `False` [here](https://github.com/Cadasta/django-jsonattrs/blob/master/jsonattrs/forms.py#L60). It will be [overwritten further down only of the field is actually required](https://github.com/Cadasta/django-jsonattrs/blob/master/jsonattrs/forms.py#L72).

**Comment by ian-ross** [comment]
Fixed in version 0.1.2.
