### ISSUE TITLE
Create Schema Update Process

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/django-jsonattrs#8]
Updating format: 

### Problem Statement

Once that we have data submitted in a project we have disabled the ability to modify the project data schema (by uploading a new xlsform file) due to security reasons, as we have no control over the changes that would be done and data consistency is then at risk. 

We need a controlled mechanism to safely update project data schemas. 

### Context / Use Case

The design of a questionnaire by a partner is in most cases an iterative process. Different versions are created and partners typically need to include new fields, change labels and fix typos. 

### User Stories

As a project manager, I want to **safely** modify the project data schema (by uploading a new xlsform or in the future with the Project Designer) when there is already data being submitted to the project. 

### Description 

A very specific set of rules need to be defined containing the allowed changes that are safe to do. 

### Link to the DR

A decision record has been created for documenting this: 
https://github.com/Cadasta/decision-records/blob/master/DR_0004_questionnaire-change-rules.md

----

Updated: 
- There is a DR for documenting this, link [here](https://github.com/Cadasta/decision-records/pull/4). 
---
In particular:
- Changes to schema selectors in foreign key-related objects should be detected and should trigger a schema update.  For instance, if you have a model class `Party` with a `JSONAttributes` field that has a field `project` that's a foreign key to the `Project` class, and the `Project` class has a field called `current_questionnaire`, then you should be able to use `project.current_questionnaire` as a schema selector and have schema updating happen on `Party` whenever the `current_questionnaire` field is changed (and the `Project` saved) in the `Project` that the `project` field points to.
- There needs to be some mechanism for value migration when schemas are updated.  There should be some way of specifying rules for migrating values of one type to values of another type (for example, when migrating from a `text` field to a `decimal` field, you might want to treat blank fields as zeros).

This is required to fix https://github.com/Cadasta/cadasta-platform/issues/640.

<hr>

Some ideas:
- The first thing seems as though it may just be a matter of adding the appropriate `pre_save` signal handlers in the right places, but some logic will be needed to deal with chains of foreign keys and cascading updates (e.g. a schema selector `project.organization.rules` would need to trigger updates whenever `project`, `project.organization` or `project.organization.rules` changes).
- For data migration, it seems as though it would make sense to have a `MigrationRule` model, keyed on "from type" and "to type" (and broken down by content type and schema selectors, just as for schemas).  You give a match regexp and a substitution regexp and data is transformed accordingly on schema updates.  A type update that's incompatible in the current version remains incompatible in the absence of a suitable rule.

**Comment by dpalomino** [comment]
Thanks a lot @ian-ross for checking this. This is becoming a serious problem, it is very typical that partners need to change things in the early stages (happened a couple of times already) and this is causing projects to get stuck in production, so needing to duplicate the project to upload the new questionnaire. 

Any chances to address this in Milestone 9?

Thanks!

**Comment by wonderchook** [comment]
@dpalomino what is being proposed is complicated. There are two use cases here:
1. There is no data collected yet (this is easy)
2. There is already data, what should we do with the information that is already collected if the type doesn't match at all with what the schema is being updated to?

**Comment by ian-ross** [comment]
The data value migration part is definitely delicate, and has potential for major catastrophe if it's misused.  The "non-primary key schema selectors in foreign key-related fields" thing is easier to fix.  I'd definitely see being able to do that part for Sprint 9.  The value migration part needs some serious thinking.  If it's done wrong, it would become possible, by misconfiguring the migration rules, to destroy data by a user uploading new XLSForms.  That would be bad.  This is one of the cases where the approach of having people edit XLSForms directly is really dangerous.  The quicker we get to a UI for setting this stuff up within the platform, the better.

**Comment by wonderchook** [comment]
Fixing the easier thing to fix, doesn't really fix the original issue. Right? (Not saying we shouldn't fix it)

What about some process where we attempt to do the migration and warn the user? The example given where a field was changed from text to decimal, if the data was actually numbers it should have migrated right over. We'd only be letting project managers do this. I'm not saying I like this solution just trying to think of a middle option.

**Comment by ian-ross** [comment]
Fixing the easy bit would fix part of the problem, I think, though not this text-to-decimal change thing.

One way to make things safe (or safer anyway) would be to strongly restrict the allowed types of migration rules.  So, for example, you could say that if you migrate from a text field to a numeric field, then if the text in the field parses OK as the relevant type of number, you carry it over, and if the field is blank, you fill it with the default value for the numeric field.  You would make it so that, if there are blank text fields, it would be mandatory to supply a default for the numeric field.

I could try writing down a set of "safe" data migration rules for people to try picking holes in.  We could perhaps set things up so that the rules are completely fixed, there are no user options to set, and the rules guarantee that there cannot be any data loss.

Does that seem like a reasonable approach?  It's not something that's going to get done in Sprint 9, though.  Perhaps the design (and arguing!) could be done, plus some prototyping of the data migration rules.  Then the final fix could be implemented in Sprint 10.

How we deploy and test this is another kettle of fish, but we'll have to think about that...

**Comment by wonderchook** [comment]
Coming up with a list of migration rules is a good start. We can then aim for a fix in Sprint 10.

**Comment by ian-ross** [comment]
OK, I'll do that.

**Comment by wonderchook** [comment]
Created a related ticket for purposes of sprint tracking: https://github.com/Cadasta/cadasta-platform/issues/654

**Comment by dpalomino** [comment]
There is a DR for documenting this, link [here](https://github.com/Cadasta/decision-records/pull/4). 

Updating the original description to include the link.

**Comment by dpalomino** [comment]
Updating format: 

### Problem Statement

Once that we have data submitted in a project we have disabled the ability to modify the project data schema (by uploading a new xlsform file) due to security reasons, as we have no control over the changes that would be done and data consistency is then at risk. 

We need a controlled mechanism to safely update project data schemas. 

### Context / Use Case

The design of a questionnaire by a partner is in most cases an iterative process. Different versions are created and partners typically need to include new fields, change labels and fix typos. 

### User Stories

As a project manager, I want to **safely** modify the project data schema (by uploading a new xlsform or in the future with the Project Designer) when there is already data being submitted to the project. 

### Description 

A very specific set of rules need to be defined containing the allowed changes that are safe to do. 

### Link to the DR

A decision record has been created for documenting this: 
https://github.com/Cadasta/decision-records/blob/master/DR_0004_questionnaire-change-rules.md
